const homepagePopular = [
    {title: 'Popular Real Estate Markets',
        body: ['Washington Real Estate', 'Chicago Real Estate', 'Dallas Real Estate', 'Los Angeles Real Estate', 'Houston Real Estate', 'Philadelphia Real Estate', 'Atlanta Real Estate', 'Phoenix Real Estate', 'Boston Real Estate', 'Miami Real Estate', 'Orlando FL Real Estate', 'San Diego Real Estate', 'Tampa Real Estate', 'Las Vegas Real Estate', 'West Palm Beach Real Estate', 'Raleigh Real Estate', 'New Haven Real Estate', 'Durham Real Estate', 'Chapel Hill Real Estate', 'Saint Petersburg FL Real Estate', 'Charlotte Real Estate', 'Denver Real Estate', 'New York City Real Estate', 'Staten Island NY Real Estate', 'Brooklyn NY Real Estate', 'Queens NY Real Estate', 'Bronx NY Real Estate', 'Manhattan NY Real Estate', 'New York State Real Estate', 'Burlington Real Estate', 'Sacramento Real Estate', 'Saint Louis Real Estate', 'San Francisco Real Estate', 'Austin TX Real Estate', 'Seattle Real Estate', 'Jacksonville FL Real Estate', 'Plano Real Estate', 'San Jose CA Real Estate']
    },
    {title: 'Popular Apartment Cities',
     body: ['Denver Apartments', 'Miami Apartments', 'Miami Beach Apartments', 'Portland OR Apartments', 'New York City Apartments', 'Bronx NY Apartments', 'Brooklyn NY Apartments', 'Manhattan NY Apartments', 'Queens NY Apartments', 'Staten Island NY Apartments', 'Tampa Apartments', 'San Diego Apartments', 'Austin Apartments', 'Houston Apartments', 'Hoboken Apartments', 'Jacksonville FL Apartments', 'Seattle Apartments', 'Washington DC Apartments', 'San Francisco Apartments', 'Chicago Apartments', 'Phoenix Apartments', 'Detroit Apartments', 'West Palm Beach Apartments', 'San Antonio Apartments', 'Stamford Apartments', 'Boca Raton Apartments', 'Santa Barbara Apartments', 'Irving Apartments', 'North Hollywood Apartments', 'Fort Worth Apartments', 'Fort Collins Apartments', 'Atlanta Apartments', 'Las Vegas Apartments', 'Sherman Oaks Apartments', 'Orlando Apartments', 'Boston Apartments', 'Dallas Apartments']
    },
    {title: 'Popular Resources',
     body: ['Homes For Sale Near Universities', 'Local Real Estate Market', 'Real Estate Mobile Apps', 'Android Rentals App', 'iPhone Rentals App', 'Full-Service Movers', 'Moving Company Search on Moving.com', 'Truck Rental', 'Assisted Living on SeniorHousingNet.com', 'Real Estate Search', 'New Home Construction Search', 'Foreclosure Search', 'Recently Sold Homes Search', 'Property Record Search', 'Apartment Rental Search', 'iPhone Real Estate App', 'Android Real Estate App']
    },
    {title: 'US Real Estate Overview & Homes for Sale',
     body: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Virgin Islands of the United States', 'Guam' , 'Puerto Rico']
    }
];

export {homepagePopular}