const apartments = [
    {id: 1, title: 'My cool apartment', description: 'My apartment description', cityId: 2, owner: 1, price: 300000, main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_baths: 4, address: '330 3rd Ave', sqft: 7500, status: 2, for_rent: false,for_sale: true, property: 'single', agent: 'Kanae Abe', agency: 'Luxury Homes International'},
    {id: 2, title: 'My nice apartment', description: 'My nice apartment description', cityId: 6, owner: 2, price: 550000, number_of_beds: 1, number_of_baths: 1, address: '128 Court St', main_image: "images/apartment/apartment_2.jpg", images: ["images/apartment/apartment_6.png", "images/apartment/apartment_7.jpg", "images/apartment/apartment_8.jpg", "images/apartment/apartment_9.jpg", "images/apartment/apartment_1.jpg"], sqft: 7500,for_rent: false, for_sale: false, property: 'farm', agent: 'Nicolas Nicolaou', agency: 'Coldwell Banker Res. Brokerage'},
    {id: 3, title: 'My cool apartment', description: 'My apartment description', cityId: 17, owner: 1, price: 1000000, main_image: "images/apartment/apartment_4.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg"], number_of_beds: 1, number_of_baths: 1, address: '3 Allenby St', sqft: 7500, status: 2, for_rent: true,for_sale: false, property: 'single', agent: 'Larry Young', agency: 'Berkshire Hathaway HomeServices'},
    {id: 4, title: 'My nice apartment', description: 'My nice apartment description', cityId: 13, owner: 2, price: 425000, number_of_beds: 4, number_of_baths: 2, address: '13 Black Cat Rd', main_image: "images/apartment/apartment_4.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_1.jpg"], sqft: 7500,for_rent: false, for_sale: true, property: 'multi', agent: 'Tomer Fridman', agency: 'Compass'},
    {id: 5, title: 'My cool apartment', description: 'My apartment description', cityId: 4, owner: 1, price: 999000, main_image: "images/apartment/apartment_4.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], number_of_beds: 5, number_of_baths: 5, address: '423 Rozeni St', sqft: 7500, status: 2, for_rent: false,for_sale: false, property: 'land', agent: 'Roger Perry', agency: 'Rodeo Realty'},
    {id: 6, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 4, price: 850000, number_of_beds: 3, number_of_baths: 3, address: '52 Zurik St', main_image: "images/apartment/apartment_5.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: true, for_sale: true, property: 'single', agent: 'Sally Forster Jones', agency: 'Compass'},
    {id: 7, title: 'My cool apartment', description: 'My apartment description', cityId: 15, owner: 1, price: 560000, main_image: "images/apartment/apartment_6.png", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], number_of_beds: 2, number_of_baths: 3, address: '41 Korab St', sqft: 7500, status: 2, for_rent: false,for_sale: true, property: 'land', agent: 'Stephanie Cobin', agency: 'Berkshire Hathaway HomeServices'},
    {id: 8, title: 'My nice apartment', description: 'My nice apartment description', cityId: 21, owner: 8, price: 1200000, number_of_beds: 3, number_of_baths: 4, address: '422 Morris St', main_image: "images/apartment/apartment_7.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: false, for_sale: false, property: 'mobile', agent: 'Richard Maslan', agency: 'Hilton & Hyland'},
    {id: 9, title: 'My cool apartment', description: 'My apartment description', cityId: 16, owner: 7, price: 900000, main_image: "images/apartment/apartment_8.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_baths: 4, address: '56 Abbey Rd', sqft: 7500, status: 2, for_rent: false, for_sale: false, property: 'condo', agent: 'Jimmy Heckenberg', agency: 'Rodeo Realty'},
    {id: 10, title: 'My nice apartment', description: 'My nice apartment description', cityId: 12, owner: 6, price: 900990, number_of_beds: 2, number_of_baths: 3, address: '15 Captain Michaels Rd', main_image: "images/apartment/apartment_9.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: true, for_sale: true, property: 'condo', agent: 'Nina Bol', agency: '360 Realty'},
    {id: 11, title: 'My cool apartment', description: 'My apartment description', cityId: 20, owner: 1, price: 1000000, main_image: "images/apartment/apartment_1.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_baths: 3, address: '39 State St', sqft: 7500, status: 2, for_rent: true, for_sale: true, property: 'condo', agent: 'Tomer Fridman', agency: 'Compass'},
    {id: 12, title: 'My nice apartment', description: 'My nice apartment description', cityId: 7, owner: 2, price: 4200000, number_of_beds: 5, number_of_baths: 2, address: '1587 Main St', main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: false, for_sale: false, property: 'condo', agent: 'Aileen Comora', agency: 'The Agency'},
    {id: 13, title: 'My cool apartment', description: 'My apartment description', cityId: 8, owner: 1, price: 2000500, main_image: "images/apartment/apartment_1.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_baths: 5, address: '8 Church Rd', sqft: 7500, status: 2, for_rent: true, for_sale: false, property: 'multi', agent: 'Peter Whyte', agency: 'NRT West, Inc'},
    {id: 14, title: 'My nice apartment', description: 'My nice apartment description', cityId: 9, owner: 2, price: 566000, number_of_beds: 3, number_of_baths: 1, address: '344 King George St', main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: true, for_sale: false, property: 'farm', agent: 'Madison Hildebrand', agency: 'Compass'},
    {id: 15, title: 'My cool apartment', description: 'My apartment description', cityId: 9, owner: 1, price: 990000, main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], number_of_beds: 2, number_of_baths: 2, address: '84 Helms Way', sqft: 7500, status: 2, for_rent: true, for_sale: false, property: 'single', agent: 'Marc Elkaim', agency: 'Barnes International Realty'},
    {id: 16, title: 'My nice apartment', description: 'My nice apartment description', cityId: 10, owner: 2, price: 900999, number_of_beds: 5, number_of_baths: 5, address: '10 Rothschild St', main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: true, for_sale: false, property: 'land', agent: 'Branden Williams', agency: 'Hilton & Hyland'},
    {id: 17, title: 'My cool apartment', description: 'My apartment description', cityId: 19, owner: 1, price: 635000, main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], number_of_beds: 3, number_of_baths: 2, address: '123 South Bay Lane', sqft: 7500, status: 2, for_rent: true, for_sale: false, property: 'condo', agent: 'Chloe Chan', agency: 'Re/Max Advanced Realty'},
    {id: 18, title: 'My nice apartment', description: 'My nice apartment description', cityId: 5, owner: 2, price: 230000, number_of_beds: 6, number_of_baths: 5, address: '27 School St', main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], sqft: 7500,for_rent: true, for_sale: false, property: 'condo', agent: 'Jon Grauman', agency: 'The Agency'},
    {id: 19, title: 'My cool apartment', description: 'My apartment description', cityId: 6, owner: 1, price: 478000, main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg"], number_of_beds: 4, number_of_baths: 3, address: '6519 Park Ave', sqft: 7500, status: 2, for_rent: true, for_sale: false, property: 'single', agent: 'Irma Velasquez', agency: 'Century 21 A Better Service'},
    {id: 20, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 2, price: 3400000, number_of_beds: 4, number_of_baths: 3, address: '37 Beach St.', main_image: "images/apartment/apartment_1.jpg", images: ["images/apartment/apartment_8.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_1.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_7.jpg"], sqft: 7500,for_rent: true, for_sale: false, property: 'mobile', agent: 'Juliet Zacarias', agency: "Sotheby's International Reality"}
];

export {apartments};